language: python
python: 3.8

services:
  - docker

branches: master

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

install:
  - pip install mkdocs mkdocs-material pymdown-extensions pygments 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - mkdocs build --verbose --clean --strict
  - docker build -t galaxygate/guides:$COMMIT .
  - docker push galaxygate/guides