site_name: 'GalaxyGate Guides'
site_description: 'GalaxyGate Guides'
site_author: 'GalaxyGate Community'
site_url: 'https://wiki.galaxygate.net'
# Configuration
theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'indigo'
  language: 'en'
  feature:
    tabs: true

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

extra_css:
  - 'extras/extra.css'
extra_javascript:
  - 'extras/extra.js'

nav:
  - Home: 'index.md'
  - Linux Basics:
      - 'basics/index.md'
      - Login: 'basics/first_login.md'
      - Creating Sudo User: 'basics/sudo_user.md'
      - Fix unable to resolve host: 'basics/fix_hostname.md'
  - Hosting:
      - 'hosting/index.md'
      - Discord:
          - Python: 'hosting/discord/python.md'
          - JavaScript: 'hosting/discord/javascript.md'
  - Games:
      - 'games/index.md'
      - Minecraft Java:
          - Paper: 'games/minecraft/java/paper.md'
          - Vanilla: 'games/minecraft/java/vanilla.md'
      - Minecraft Bedrock:
          - Bedrock: 'games/minecraft/bedrock/bedrock.md'
          - Pocketmine: 'games/minecraft/bedrock/pocketmine.md'
          - Nukkit: 'games/minecraft/bedrock/nukkit.md'
      - Terraria:
          - PC: 'games/terraria/pc.md'
